/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@ionic/core';


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  CalendarComponent as CheftonicCalendar
} from './components/calendar/calendar';

declare global {
  interface HTMLCheftonicCalendarElement extends CheftonicCalendar, HTMLStencilElement {
  }
  var HTMLCheftonicCalendarElement: {
    prototype: HTMLCheftonicCalendarElement;
    new (): HTMLCheftonicCalendarElement;
  };
  interface HTMLElementTagNameMap {
    "cheftonic-calendar": HTMLCheftonicCalendarElement;
  }
  interface ElementTagNameMap {
    "cheftonic-calendar": HTMLCheftonicCalendarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "cheftonic-calendar": JSXElements.CheftonicCalendarAttributes;
    }
  }
  namespace JSXElements {
    export interface CheftonicCalendarAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  HourMinuteComponent as CheftonicHourMinute
} from './components/hour-minute/hour-minute';

declare global {
  interface HTMLCheftonicHourMinuteElement extends CheftonicHourMinute, HTMLStencilElement {
  }
  var HTMLCheftonicHourMinuteElement: {
    prototype: HTMLCheftonicHourMinuteElement;
    new (): HTMLCheftonicHourMinuteElement;
  };
  interface HTMLElementTagNameMap {
    "cheftonic-hour-minute": HTMLCheftonicHourMinuteElement;
  }
  interface ElementTagNameMap {
    "cheftonic-hour-minute": HTMLCheftonicHourMinuteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "cheftonic-hour-minute": JSXElements.CheftonicHourMinuteAttributes;
    }
  }
  namespace JSXElements {
    export interface CheftonicHourMinuteAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MakeBookingComponent as MakeBooking
} from './components/make-booking/make-booking';

declare global {
  interface HTMLMakeBookingElement extends MakeBooking, HTMLStencilElement {
  }
  var HTMLMakeBookingElement: {
    prototype: HTMLMakeBookingElement;
    new (): HTMLMakeBookingElement;
  };
  interface HTMLElementTagNameMap {
    "make-booking": HTMLMakeBookingElement;
  }
  interface ElementTagNameMap {
    "make-booking": HTMLMakeBookingElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "make-booking": JSXElements.MakeBookingAttributes;
    }
  }
  namespace JSXElements {
    export interface MakeBookingAttributes extends HTMLAttributes {
      restid?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
